#red-config的测试配置文件
red:
  remark: '{cipher}AQBQxGPF/QVRLJOhRF+mBlSYfBL7bQqD5ERHrspHVI7zkKL8zr0ew65CwaBJ2DrIvmXFqASSHgtDIay7+43MsxlhrTO4ktrdMFAeO4XPSf4Kbvt7tbW+iwI8Wa3+KnPdsC55B1Ovs/qW13NUf44hkW7b+VMgRbsQNfkKUivk/3ze6ryy/x3njC3CWKr9KeGKqy52ghDwLsC9YgpOtGgtutCtvI+Xc51YYJ51S+hrsOacYy/L0jn57RncqXZNZ7/7rHQtzoQLySiTkbeiVhYw2sZRhYRB3fxF9XInEuhLZYd/ZZ+Pu2YyhlvOwVHZKh18jTU+zwJmZp6TR9CzLCl79G0CUjoLk6sDBK32SDnKJxjPcYI0os8xxBFysIW2fC/AdG4='
